{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gt/gt_{{ version }}.tar.gz
  sha256: 5eb74e134101cc74b8764252b8f4693a19e58f670b2f286b35cdb4d0ad0de9f9

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-base64enc >=0.1_3
    - r-bigd >=0.1
    - r-bitops >=1.0.7
    - r-cli >=3.4.1
    - r-commonmark >=1.8
    - r-dplyr >=1.0.8
    - r-fs >=1.5.2
    - r-ggplot2 >=3.3.5
    - r-glue >=1.6.1
    - r-htmltools >=0.5.2
    - r-juicyjuice >=0.1.0
    - r-magrittr >=2.0.2
    - r-rlang >=1.0.2
    - r-sass >=0.4.1
    - r-scales >=1.2.0
    - r-tibble >=3.1.6
    - r-tidyselect >=1.1.1
  run:
    - r-base
    - r-base64enc >=0.1_3
    - r-bigd >=0.1
    - r-bitops >=1.0.7
    - r-cli >=3.4.1
    - r-commonmark >=1.8
    - r-dplyr >=1.0.8
    - r-fs >=1.5.2
    - r-ggplot2 >=3.3.5
    - r-glue >=1.6.1
    - r-htmltools >=0.5.2
    - r-juicyjuice >=0.1.0
    - r-magrittr >=2.0.2
    - r-rlang >=1.0.2
    - r-sass >=0.4.1
    - r-scales >=1.2.0
    - r-tibble >=3.1.6
    - r-tidyselect >=1.1.1

test:
  commands:
    - $R -e "library('gt')"           # [not win]
    - "\"%R%\" -e \"library('gt')\""  # [win]

about:
  home: https://github.com/rstudio/gt
  license: MIT
  summary: |
    Build display tables from tabular data using with an easy-to-use API. With its progressive
    approach, we can construct display tables with a clear separation of concerns: you
    don''t have to decide how the tabular data gets transformed and structured whilst
    also worrying about aesthetics.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Type: Package
# Package: gt
# Version: 0.2.0.5
# Title: Easily Create Presentation-Ready Display Tables
# Description: Build display tables from tabular data using with an easy-to-use API. With its progressive approach, we can construct display tables with a clear separation of concerns: you don't have to decide how the tabular data gets transformed and structured whilst also worrying about aesthetics.
# Authors@R: c( person("Richard", "Iannone", , "rich@rstudio.com", c("aut", "cre"), comment = c(ORCID = "0000-0003-3925-190X")), person("Joe", "Cheng", , "joe@rstudio.com", "aut"), person("Barret", "Schloerke", , "barret@rstudio.com", "aut", comment = c(ORCID = "0000-0001-9986-114X")), person("RStudio", role = c("cph", "fnd")) )
# License: MIT + file LICENSE
# URL: https://github.com/rstudio/gt
# BugReports: https://github.com/rstudio/gt/issues
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# RoxygenNote: 7.1.0
# Depends: R (>= 3.2.0)
# Imports: checkmate (>= 2.0.0), commonmark (>= 1.7), dplyr (>= 0.8.5), fs (>= 1.3.2), ggplot2 (>= 3.3.0), glue (>= 1.3.2), htmltools (>= 0.4.0), magrittr (>= 1.5), rlang (>= 0.4.5), sass (>= 0.1.1), scales (>= 1.1.0), stringr (>= 1.3.1), tibble (>= 3.0.0), tidyselect (>= 1.0.0)
# Suggests: knitr, paletteer, testthat (>= 2.1.0), RColorBrewer, rmarkdown, rvest, shiny, tidyr, webshot, xml2
# Collate: 'as_data_frame.R' 'base64.R' 'build_data.R' 'compile_scss.R' 'data_color.R' 'datasets.R' 'dt__.R' 'dt_body.R' 'dt_boxhead.R' 'dt_cols_merge.R' 'dt_data.R' 'dt_footnotes.R' 'dt_formats.R' 'dt_groups_rows.R' 'dt_has_built.R' 'dt_heading.R' 'dt_options.R' 'dt_row_groups.R' 'dt_source_notes.R' 'dt_spanners.R' 'dt_stub_df.R' 'dt_stub_others.R' 'dt_stubhead.R' 'dt_styles.R' 'dt_summary.R' 'dt_transforms.R' 'export.R' 'format_data.R' 'gt-package.R' 'gt.R' 'gt_preview.R' 'helpers.R' 'image.R' 'info_tables.R' 'location_methods.R' 'modify_columns.R' 'modify_rows.R' 'tab_create_modify.R' 'opts.R' 'print.R' 'reexports.R' 'render_as_html.R' 'resolver.R' 'shiny.R' 'summary_rows.R' 'text_transform.R' 'utils.R' 'utils_formatters.R' 'utils_general_str_formatting.R' 'utils_pipe.R' 'utils_render_common.R' 'utils_render_footnotes.R' 'utils_render_html.R' 'utils_render_latex.R' 'utils_render_rtf.R' 'zzz.R'
# NeedsCompilation: no
# Packaged: 2020-03-31 04:35:21 UTC; rich
# Author: Richard Iannone [aut, cre] (<https://orcid.org/0000-0003-3925-190X>), Joe Cheng [aut], Barret Schloerke [aut] (<https://orcid.org/0000-0001-9986-114X>), RStudio [cph, fnd]
# Maintainer: Richard Iannone <rich@rstudio.com>
# Repository: CRAN
# Date/Publication: 2020-03-31 10:10:02 UTC
